M48
; DRILL file {KiCad (6.0.10)} date Sun Jun 11 20:59:23 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-11T20:59:23+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.10)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X105.435Y-75.413
X106.02Y-112.928
X235.864Y-73.558
X236.017Y-116.053
T0
M30
